{{- if .Values.env.SESSION_SECRET }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scriptorium.fullname" . }}-secret
  labels:
    {{- include "scriptorium.labels" . | nindent 4 }}
type: Opaque
stringData:
  session-secret: {{ .Values.env.SESSION_SECRET | quote }}
{{- end }}
